# Exported from Render on 2024-08-11T11:10:31Z
services:
- type: web
  name: CommunityEventsPlatform
  runtime: python
  repo: https://github.com/Rajan08091998/CommunityEventsPlatform
  plan: free
  envVars:
  - key: DB_DATABASE
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DEBUG
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_NAME
    sync: false
  - key: DB_HOST
    sync: false
  region: singapore
  buildCommand: ./build.sh
  startCommand: python manage.py runserver 0.0.0.0:8000
  healthCheckPath: /ht
version: "1"
